<?php

namespace Database\Seeders;

use App\Models\Branch;
use App\Models\BriefingTask;
use Illuminate\Database\Seeder;

class BriefingTasksSeeder extends Seeder
{
    public function run(): void
    {
        $branchIds = Branch::pluck('id', 'name');

        $tokoUtama = $branchIds['Toko Utama'] ?? null;
        $cabangSelatan = $branchIds['Cabang Selatan'] ?? null;

        $tasks = [
            // ── Global (null branch) ─────────────────────────────────────
            ['branch_id' => null,          'key' => 'daily_selfie_pagi',               'label' => 'Absen Briefing Pagi (09.00)',                                       'group' => null,              'group_label' => null,             'period' => 'daily',   'weight' => '15.00', 'submission_type' => 'camera_only', 'note_type' => 'Foto Selfie Briefing',                          'is_active' => true,  'sort_order' => 1,  'deadline_enabled' => true,  'deadline_day' => null, 'deadline_time' => '09:00:00'],
            ['branch_id' => null,          'key' => 'daily_selfie_sore',               'label' => 'Absen Briefing Sore (15.30)',                                       'group' => null,              'group_label' => null,             'period' => 'daily',   'weight' => '15.00', 'submission_type' => 'camera_only', 'note_type' => 'Foto Selfie Briefing',                          'is_active' => true,  'sort_order' => 2,  'deadline_enabled' => true,  'deadline_day' => null, 'deadline_time' => '15:30:00'],
            ['branch_id' => null,          'key' => 'daily_detail_briefing',           'label' => 'Detail Briefing',                                                   'group' => null,              'group_label' => null,             'period' => 'daily',   'weight' => null,    'submission_type' => 'text_only',   'note_type' => 'Catatan Teks Briefing',                         'is_active' => true,  'sort_order' => 3,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => null,          'key' => 'monthly_gm_kpi',                  'label' => 'General Meeting: Key Performance Indicator (KPI)',                   'group' => null,              'group_label' => null,             'period' => 'monthly', 'weight' => '15.00', 'submission_type' => 'camera_only', 'note_type' => 'Foto Weekly Meeting PIC / General Meeting',     'is_active' => true,  'sort_order' => 1,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => null,          'key' => 'monthly_cleaning_chiller',        'label' => 'Cuci Komponen Showcase Chiller',                                     'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => '15.00', 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 2,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => null,          'key' => 'monthly_cleaning_docs',           'label' => 'Bersihkan Filter Showcase Display',                                  'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null,    'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 3,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => null,          'key' => 'monthly_cleaning_floor',          'label' => 'Bersihkan Lantai & Dinding dari Spot Hitam',                         'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null,    'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 4,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => null,          'key' => 'monthly_cleaning_freezer',        'label' => 'Kuras Bunga Es Freezer',                                             'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null,    'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 5,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => null,          'key' => 'monthly_cleaning_sink',           'label' => 'Poles Sink & Wastafel',                                              'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null,    'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 6,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => null,          'key' => 'monthly_cleaning_equipment',      'label' => 'Deep Cleaning Dispenser, Kompor & Blender',                          'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null,    'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 7,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => null,          'key' => 'monthly_cleaning_coffee',         'label' => 'Deep Cleaning Mesin Kopi',                                           'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null,    'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 8,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => null,          'key' => 'monthly_cleaning_sofa',           'label' => 'Vacuum Sofa',                                                        'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null,    'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 9,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => null,          'key' => 'monthly_cleaning_discard',        'label' => 'Sortir Barang Tidak Terpakai / Diloak',                              'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null,    'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 10, 'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => null,          'key' => 'monthly_cleaning_specific',       'label' => 'Deep Cleaning Item Spesifik Store',                                  'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null,    'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 11, 'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => null,          'key' => 'weekly_cleaning',                 'label' => 'Weekly Cleaning',                                                    'group' => null,              'group_label' => null,             'period' => 'weekly',  'weight' => '20.00', 'submission_type' => 'camera_only', 'note_type' => 'Foto Area yang Dibersihkan',                    'is_active' => false, 'sort_order' => 1,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => null,          'key' => 'weekly_wm_pic',                   'label' => 'Weekly Meeting PIC (Evaluasi Staff, Administrasi dan Sales)',         'group' => null,              'group_label' => null,             'period' => 'weekly',  'weight' => '20.00', 'submission_type' => 'camera_only', 'note_type' => 'Foto Weekly Meeting PIC / General Meeting',     'is_active' => true,  'sort_order' => 2,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => null,          'key' => 'weekly_schedule',                 'label' => 'Weekly Schedule',                                                    'group' => null,              'group_label' => null,             'period' => 'weekly',  'weight' => null,    'submission_type' => 'camera_only', 'note_type' => 'Foto Jadwal Mingguan',                          'is_active' => true,  'sort_order' => 3,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => null,          'key' => 'weekly_cleaning_kondensor',       'label' => 'Bersihkan Filter Kondensor Showcase Display',                        'group' => 'weekly_cleaning', 'group_label' => 'Weekly Cleaning', 'period' => 'weekly',  'weight' => null,    'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 4,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => null,          'key' => 'weekly_cleaning_mesin_kopi',      'label' => 'Bersihkan Mesin Kopi (Puro)',                                         'group' => 'weekly_cleaning', 'group_label' => 'Weekly Cleaning', 'period' => 'weekly',  'weight' => null,    'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 5,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => null,          'key' => 'weekly_cleaning_genset',          'label' => 'Panaskan Genset 15 Menit',                                           'group' => 'weekly_cleaning', 'group_label' => 'Weekly Cleaning', 'period' => 'weekly',  'weight' => null,    'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 6,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => null,          'key' => 'weekly_cleaning_tempat_sampah',   'label' => 'Cuci Tempat Sampah & Keset',                                          'group' => 'weekly_cleaning', 'group_label' => 'Weekly Cleaning', 'period' => 'weekly',  'weight' => null,    'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 7,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => null,          'key' => 'weekly_cleaning_showcase_chiller', 'label' => 'Bersihkan Showcase Chiller Inventory',                               'group' => 'weekly_cleaning', 'group_label' => 'Weekly Cleaning', 'period' => 'weekly',  'weight' => null,    'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 8,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],

            // ── Toko Utama ───────────────────────────────────────────────
            ['branch_id' => $tokoUtama,    'key' => 'daily_selfie_pagi_2_2',               'label' => 'Absen Briefing Pagi (09.00)',                                   'group' => null,              'group_label' => null,             'period' => 'daily',   'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Selfie Briefing',                          'is_active' => true,  'sort_order' => 1,  'deadline_enabled' => true,  'deadline_day' => null, 'deadline_time' => '09:00:00'],
            ['branch_id' => $tokoUtama,    'key' => 'daily_selfie_sore_2_2',               'label' => 'Absen Briefing Sore (15.30)',                                   'group' => null,              'group_label' => null,             'period' => 'daily',   'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Selfie Briefing',                          'is_active' => true,  'sort_order' => 2,  'deadline_enabled' => true,  'deadline_day' => null, 'deadline_time' => '15:30:00'],
            ['branch_id' => $tokoUtama,    'key' => 'daily_detail_briefing_2_2',           'label' => 'Detail Briefing',                                               'group' => null,              'group_label' => null,             'period' => 'daily',   'weight' => null, 'submission_type' => 'text_only',   'note_type' => 'Catatan Teks Briefing',                         'is_active' => true,  'sort_order' => 3,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $tokoUtama,    'key' => 'monthly_gm_kpi_2_2',                  'label' => 'General Meeting: Key Performance Indicator (KPI)',               'group' => null,              'group_label' => null,             'period' => 'monthly', 'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Weekly Meeting PIC / General Meeting',     'is_active' => true,  'sort_order' => 1,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $tokoUtama,    'key' => 'monthly_cleaning_chiller_2_2',        'label' => 'Cuci Komponen Showcase Chiller',                                 'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 2,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $tokoUtama,    'key' => 'monthly_cleaning_docs_2_2',           'label' => 'Bersihkan Filter Showcase Display',                              'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 3,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $tokoUtama,    'key' => 'monthly_cleaning_floor_2_2',          'label' => 'Bersihkan Lantai & Dinding dari Spot Hitam',                     'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 4,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $tokoUtama,    'key' => 'monthly_cleaning_freezer_2_2',        'label' => 'Kuras Bunga Es Freezer',                                         'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 5,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $tokoUtama,    'key' => 'monthly_cleaning_sink_2_2',           'label' => 'Poles Sink & Wastafel',                                          'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 6,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $tokoUtama,    'key' => 'monthly_cleaning_equipment_2_2',      'label' => 'Deep Cleaning Dispenser, Kompor & Blender',                      'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 7,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $tokoUtama,    'key' => 'monthly_cleaning_coffee_2_2',         'label' => 'Deep Cleaning Mesin Kopi',                                       'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 8,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $tokoUtama,    'key' => 'monthly_cleaning_sofa_2_2',           'label' => 'Vacuum Sofa',                                                    'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 9,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $tokoUtama,    'key' => 'monthly_cleaning_discard_2_2',        'label' => 'Sortir Barang Tidak Terpakai / Diloak',                          'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 10, 'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $tokoUtama,    'key' => 'monthly_cleaning_specific_2_2',       'label' => 'Deep Cleaning Item Spesifik Store',                              'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 11, 'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $tokoUtama,    'key' => 'weekly_cleaning_2_2',                 'label' => 'Weekly Cleaning',                                                'group' => null,              'group_label' => null,             'period' => 'weekly',  'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Area yang Dibersihkan',                    'is_active' => false, 'sort_order' => 1,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $tokoUtama,    'key' => 'weekly_wm_pic_2_2',                   'label' => 'Weekly Meeting PIC (Evaluasi Staff, Administrasi dan Sales)',     'group' => null,              'group_label' => null,             'period' => 'weekly',  'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Weekly Meeting PIC / General Meeting',     'is_active' => true,  'sort_order' => 2,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $tokoUtama,    'key' => 'weekly_schedule_2_2',                 'label' => 'Weekly Schedule',                                                'group' => null,              'group_label' => null,             'period' => 'weekly',  'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Jadwal Mingguan',                          'is_active' => true,  'sort_order' => 3,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $tokoUtama,    'key' => 'weekly_cleaning_kondensor_2_2',       'label' => 'Bersihkan Filter Kondensor Showcase Display',                    'group' => 'weekly_cleaning', 'group_label' => 'Weekly Cleaning', 'period' => 'weekly',  'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 4,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $tokoUtama,    'key' => 'weekly_cleaning_mesin_kopi_2_2',      'label' => 'Bersihkan Mesin Kopi (Puro)',                                     'group' => 'weekly_cleaning', 'group_label' => 'Weekly Cleaning', 'period' => 'weekly',  'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 5,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $tokoUtama,    'key' => 'weekly_cleaning_genset_2_2',          'label' => 'Panaskan Genset 15 Menit',                                       'group' => 'weekly_cleaning', 'group_label' => 'Weekly Cleaning', 'period' => 'weekly',  'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 6,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $tokoUtama,    'key' => 'weekly_cleaning_tempat_sampah_2_2',   'label' => 'Cuci Tempat Sampah & Keset',                                      'group' => 'weekly_cleaning', 'group_label' => 'Weekly Cleaning', 'period' => 'weekly',  'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 7,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $tokoUtama,    'key' => 'weekly_cleaning_showcase_chiller_2_2', 'label' => 'Bersihkan Showcase Chiller Inventory',                           'group' => 'weekly_cleaning', 'group_label' => 'Weekly Cleaning', 'period' => 'weekly',  'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 8,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],

            // ── Cabang Selatan ───────────────────────────────────────────
            ['branch_id' => $cabangSelatan, 'key' => 'daily_selfie_pagi_2',               'label' => 'Absen Briefing Pagi (10.00)',                                       'group' => null,              'group_label' => null,             'period' => 'daily',   'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Selfie Briefing',                          'is_active' => true,  'sort_order' => 1,  'deadline_enabled' => true,  'deadline_day' => null, 'deadline_time' => '09:00:00'],
            ['branch_id' => $cabangSelatan, 'key' => 'daily_selfie_sore_2',               'label' => 'Absen Briefing Sore (15.30)',                                       'group' => null,              'group_label' => null,             'period' => 'daily',   'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Selfie Briefing',                          'is_active' => true,  'sort_order' => 2,  'deadline_enabled' => true,  'deadline_day' => null, 'deadline_time' => '15:30:00'],
            ['branch_id' => $cabangSelatan, 'key' => 'daily_detail_briefing_2',           'label' => 'Detail Briefing',                                                   'group' => null,              'group_label' => null,             'period' => 'daily',   'weight' => null, 'submission_type' => 'text_only',   'note_type' => 'Catatan Teks Briefing',                         'is_active' => true,  'sort_order' => 3,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $cabangSelatan, 'key' => 'monthly_gm_kpi_2',                  'label' => 'General Meeting: Key Performance Indicator (KPI)',                   'group' => null,              'group_label' => null,             'period' => 'monthly', 'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Weekly Meeting PIC / General Meeting',     'is_active' => true,  'sort_order' => 1,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $cabangSelatan, 'key' => 'monthly_cleaning_chiller_2',        'label' => 'Cuci Komponen Showcase Chiller',                                     'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 2,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $cabangSelatan, 'key' => 'monthly_cleaning_docs_2',           'label' => 'Bersihkan Filter Showcase Display',                                  'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 3,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $cabangSelatan, 'key' => 'monthly_cleaning_floor_2',          'label' => 'Bersihkan Lantai & Dinding dari Spot Hitam',                         'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 4,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $cabangSelatan, 'key' => 'monthly_cleaning_freezer_2',        'label' => 'Kuras Bunga Es Freezer',                                             'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 5,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $cabangSelatan, 'key' => 'monthly_cleaning_sink_2',           'label' => 'Poles Sink & Wastafel',                                              'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 6,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $cabangSelatan, 'key' => 'monthly_cleaning_equipment_2',      'label' => 'Deep Cleaning Dispenser, Kompor & Blender',                          'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 7,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $cabangSelatan, 'key' => 'monthly_cleaning_coffee_2',         'label' => 'Deep Cleaning Mesin Kopi',                                           'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 8,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $cabangSelatan, 'key' => 'monthly_cleaning_sofa_2',           'label' => 'Vacuum Sofa',                                                        'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 9,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $cabangSelatan, 'key' => 'monthly_cleaning_discard_2',        'label' => 'Sortir Barang Tidak Terpakai / Diloak',                              'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 10, 'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $cabangSelatan, 'key' => 'monthly_cleaning_specific_2',       'label' => 'Deep Cleaning Item Spesifik Store',                                  'group' => 'general_cleaning', 'group_label' => 'General Cleaning', 'period' => 'monthly', 'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 11, 'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $cabangSelatan, 'key' => 'weekly_cleaning_2',                 'label' => 'Weekly Cleaning',                                                    'group' => 'weekly_cleaning', 'group_label' => 'Weekly Cleaning', 'period' => 'weekly',  'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Area yang Dibersihkan',                    'is_active' => false, 'sort_order' => 1,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $cabangSelatan, 'key' => 'weekly_wm_pic_2',                   'label' => 'Weekly Meeting PIC (Evaluasi Staff, Administrasi dan Sales)',         'group' => null,              'group_label' => null,             'period' => 'weekly',  'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Weekly Meeting PIC / General Meeting',     'is_active' => true,  'sort_order' => 2,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $cabangSelatan, 'key' => 'weekly_schedule_2',                 'label' => 'Weekly Schedule',                                                    'group' => null,              'group_label' => null,             'period' => 'weekly',  'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Jadwal Mingguan',                          'is_active' => true,  'sort_order' => 3,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $cabangSelatan, 'key' => 'weekly_cleaning_kondensor_2',       'label' => 'Bersihkan Filter Kondensor Showcase Display',                        'group' => 'weekly_cleaning', 'group_label' => 'Weekly Cleaning', 'period' => 'weekly',  'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 4,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $cabangSelatan, 'key' => 'weekly_cleaning_mesin_kopi_2',      'label' => 'Bersihkan Mesin Kopi (Puro)',                                         'group' => 'weekly_cleaning', 'group_label' => 'Weekly Cleaning', 'period' => 'weekly',  'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 5,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $cabangSelatan, 'key' => 'weekly_cleaning_genset_2',          'label' => 'Panaskan Genset 15 Menit',                                           'group' => 'weekly_cleaning', 'group_label' => 'Weekly Cleaning', 'period' => 'weekly',  'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 6,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $cabangSelatan, 'key' => 'weekly_cleaning_tempat_sampah_2',   'label' => 'Cuci Tempat Sampah & Keset',                                          'group' => 'weekly_cleaning', 'group_label' => 'Weekly Cleaning', 'period' => 'weekly',  'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 7,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
            ['branch_id' => $cabangSelatan, 'key' => 'weekly_cleaning_showcase_chiller_2', 'label' => 'Bersihkan Showcase Chiller Inventory',                               'group' => 'weekly_cleaning', 'group_label' => 'Weekly Cleaning', 'period' => 'weekly',  'weight' => null, 'submission_type' => 'camera_only', 'note_type' => 'Foto Bukti Cleaning',                           'is_active' => true,  'sort_order' => 8,  'deadline_enabled' => false, 'deadline_day' => null, 'deadline_time' => null],
        ];

        BriefingTask::upsert(
            $tasks,
            uniqueBy: ['key'],
            update: ['branch_id', 'label', 'group', 'group_label', 'period', 'weight', 'submission_type', 'note_type', 'is_active', 'sort_order', 'deadline_enabled', 'deadline_day', 'deadline_time'],
        );

        BriefingTask::query()->where('period', 'weekly')->update([
            'deadline_enabled' => true,
            'deadline_day' => 7,
            'deadline_time' => '23:59:00',
        ]);
        BriefingTask::query()->where('period', 'monthly')->update([
            'deadline_enabled' => true,
            'deadline_day' => 0,
            'deadline_time' => '23:59:00',
        ]);
        BriefingTask::clearCache();
    }
}
