<?php

namespace Database\Seeders;

use App\Models\BriefingTask;
use Illuminate\Database\Seeder;

class BriefingTasksSeeder extends Seeder
{
    public function run(): void
    {
        $tasks = [
            // ── Daily ────────────────────────────────────────────────────
            [
                'key' => 'daily_selfie_pagi',
                'label' => 'Absen Briefing Pagi (09.00)',
                'period' => 'daily',
                'submission_type' => 'camera_only',
                'note_type' => 'Foto Selfie Briefing',
                'group' => null,
                'group_label' => null,
                'sort_order' => 1,
                'deadline_time' => '09:00',
                'deadline_day' => null,
                'deadline_enabled' => true,
            ],
            [
                'key' => 'daily_selfie_sore',
                'label' => 'Absen Briefing Sore (15.30)',
                'period' => 'daily',
                'submission_type' => 'camera_only',
                'note_type' => 'Foto Selfie Briefing',
                'group' => null,
                'group_label' => null,
                'sort_order' => 2,
                'deadline_time' => '15:30',
                'deadline_day' => null,
                'deadline_enabled' => true,
            ],
            [
                'key' => 'daily_detail_briefing',
                'label' => 'Detail Briefing',
                'period' => 'daily',
                'submission_type' => 'text_only',
                'note_type' => 'Catatan Teks Briefing',
                'group' => null,
                'group_label' => null,
                'sort_order' => 3,
                'deadline_time' => null,
                'deadline_day' => null,
                'deadline_enabled' => false,
            ],

            // ── Weekly ───────────────────────────────────────────────────
            [
                'key' => 'weekly_cleaning',
                'label' => 'Weekly Cleaning',
                'period' => 'weekly',
                'submission_type' => 'camera_only',
                'note_type' => 'Foto Area yang Dibersihkan',
                'group' => null,
                'group_label' => null,
                'sort_order' => 1,
                'deadline_time' => null,
                'deadline_day' => null,
                'deadline_enabled' => false,
                'is_active' => false,
            ],
            [
                'key' => 'weekly_cleaning_kondensor',
                'label' => 'Bersihkan Filter Kondensor Showcase Display',
                'period' => 'weekly',
                'submission_type' => 'camera_only',
                'note_type' => 'Foto Bukti Cleaning',
                'group' => 'weekly_cleaning',
                'group_label' => 'Weekly Cleaning',
                'sort_order' => 4,
                'deadline_time' => null,
                'deadline_day' => null,
                'deadline_enabled' => false,
            ],
            [
                'key' => 'weekly_cleaning_mesin_kopi',
                'label' => 'Bersihkan Mesin Kopi (Puro)',
                'period' => 'weekly',
                'submission_type' => 'camera_only',
                'note_type' => 'Foto Bukti Cleaning',
                'group' => 'weekly_cleaning',
                'group_label' => 'Weekly Cleaning',
                'sort_order' => 5,
                'deadline_time' => null,
                'deadline_day' => null,
                'deadline_enabled' => false,
            ],
            [
                'key' => 'weekly_cleaning_genset',
                'label' => 'Panaskan Genset 15 Menit',
                'period' => 'weekly',
                'submission_type' => 'camera_only',
                'note_type' => 'Foto Bukti Cleaning',
                'group' => 'weekly_cleaning',
                'group_label' => 'Weekly Cleaning',
                'sort_order' => 6,
                'deadline_time' => null,
                'deadline_day' => null,
                'deadline_enabled' => false,
            ],
            [
                'key' => 'weekly_cleaning_tempat_sampah',
                'label' => 'Cuci Tempat Sampah & Keset',
                'period' => 'weekly',
                'submission_type' => 'camera_only',
                'note_type' => 'Foto Bukti Cleaning',
                'group' => 'weekly_cleaning',
                'group_label' => 'Weekly Cleaning',
                'sort_order' => 7,
                'deadline_time' => null,
                'deadline_day' => null,
                'deadline_enabled' => false,
            ],
            [
                'key' => 'weekly_cleaning_showcase_chiller',
                'label' => 'Bersihkan Showcase Chiller Inventory',
                'period' => 'weekly',
                'submission_type' => 'camera_only',
                'note_type' => 'Foto Bukti Cleaning',
                'group' => 'weekly_cleaning',
                'group_label' => 'Weekly Cleaning',
                'sort_order' => 8,
                'deadline_time' => null,
                'deadline_day' => null,
                'deadline_enabled' => false,
            ],
            [
                'key' => 'weekly_wm_pic',
                'label' => 'Weekly Meeting PIC (Evaluasi Staff, Administrasi dan Sales)',
                'period' => 'weekly',
                'submission_type' => 'camera_only',
                'note_type' => 'Foto Weekly Meeting PIC / General Meeting',
                'group' => null,
                'group_label' => null,
                'sort_order' => 2,
                'deadline_time' => null,
                'deadline_day' => null,
                'deadline_enabled' => false,
            ],
            [
                'key' => 'weekly_schedule',
                'label' => 'Weekly Schedule',
                'period' => 'weekly',
                'submission_type' => 'camera_only',
                'note_type' => 'Foto Jadwal Mingguan',
                'group' => null,
                'group_label' => null,
                'sort_order' => 3,
                'deadline_time' => null,
                'deadline_day' => null,
                'deadline_enabled' => false,
            ],

            // ── Monthly ──────────────────────────────────────────────────
            [
                'key' => 'monthly_gm_kpi',
                'label' => 'General Meeting: Key Performance Indicator (KPI)',
                'period' => 'monthly',
                'submission_type' => 'camera_only',
                'note_type' => 'Foto Weekly Meeting PIC / General Meeting',
                'group' => null,
                'group_label' => null,
                'sort_order' => 1,
                'deadline_time' => null,
                'deadline_day' => null,
                'deadline_enabled' => false,
            ],
            [
                'key' => 'monthly_cleaning_chiller',
                'label' => 'Cuci Komponen Showcase Chiller',
                'period' => 'monthly',
                'submission_type' => 'camera_only',
                'note_type' => 'Foto Bukti Cleaning',
                'group' => 'general_cleaning',
                'group_label' => 'General Cleaning',
                'sort_order' => 2,
                'deadline_time' => null,
                'deadline_day' => null,
                'deadline_enabled' => false,
            ],
            [
                'key' => 'monthly_cleaning_docs',
                'label' => 'Bersihkan Filter Showcase Display',
                'period' => 'monthly',
                'submission_type' => 'camera_only',
                'note_type' => 'Foto Bukti Cleaning',
                'group' => 'general_cleaning',
                'group_label' => 'General Cleaning',
                'sort_order' => 3,
                'deadline_time' => null,
                'deadline_day' => null,
                'deadline_enabled' => false,
            ],
            [
                'key' => 'monthly_cleaning_floor',
                'label' => 'Bersihkan Lantai & Dinding dari Spot Hitam',
                'period' => 'monthly',
                'submission_type' => 'camera_only',
                'note_type' => 'Foto Bukti Cleaning',
                'group' => 'general_cleaning',
                'group_label' => 'General Cleaning',
                'sort_order' => 4,
                'deadline_time' => null,
                'deadline_day' => null,
                'deadline_enabled' => false,
            ],
            [
                'key' => 'monthly_cleaning_freezer',
                'label' => 'Kuras Bunga Es Freezer',
                'period' => 'monthly',
                'submission_type' => 'camera_only',
                'note_type' => 'Foto Bukti Cleaning',
                'group' => 'general_cleaning',
                'group_label' => 'General Cleaning',
                'sort_order' => 5,
                'deadline_time' => null,
                'deadline_day' => null,
                'deadline_enabled' => false,
            ],
            [
                'key' => 'monthly_cleaning_sink',
                'label' => 'Poles Sink & Wastafel',
                'period' => 'monthly',
                'submission_type' => 'camera_only',
                'note_type' => 'Foto Bukti Cleaning',
                'group' => 'general_cleaning',
                'group_label' => 'General Cleaning',
                'sort_order' => 6,
                'deadline_time' => null,
                'deadline_day' => null,
                'deadline_enabled' => false,
            ],
            [
                'key' => 'monthly_cleaning_equipment',
                'label' => 'Deep Cleaning Dispenser, Kompor & Blender',
                'period' => 'monthly',
                'submission_type' => 'camera_only',
                'note_type' => 'Foto Bukti Cleaning',
                'group' => 'general_cleaning',
                'group_label' => 'General Cleaning',
                'sort_order' => 7,
                'deadline_time' => null,
                'deadline_day' => null,
                'deadline_enabled' => false,
            ],
            [
                'key' => 'monthly_cleaning_coffee',
                'label' => 'Deep Cleaning Mesin Kopi',
                'period' => 'monthly',
                'submission_type' => 'camera_only',
                'note_type' => 'Foto Bukti Cleaning',
                'group' => 'general_cleaning',
                'group_label' => 'General Cleaning',
                'sort_order' => 8,
                'deadline_time' => null,
                'deadline_day' => null,
                'deadline_enabled' => false,
            ],
            [
                'key' => 'monthly_cleaning_sofa',
                'label' => 'Vacuum Sofa',
                'period' => 'monthly',
                'submission_type' => 'camera_only',
                'note_type' => 'Foto Bukti Cleaning',
                'group' => 'general_cleaning',
                'group_label' => 'General Cleaning',
                'sort_order' => 9,
                'deadline_time' => null,
                'deadline_day' => null,
                'deadline_enabled' => false,
            ],
            [
                'key' => 'monthly_cleaning_discard',
                'label' => 'Sortir Barang Tidak Terpakai / Diloak',
                'period' => 'monthly',
                'submission_type' => 'camera_only',
                'note_type' => 'Foto Bukti Cleaning',
                'group' => 'general_cleaning',
                'group_label' => 'General Cleaning',
                'sort_order' => 10,
                'deadline_time' => null,
                'deadline_day' => null,
                'deadline_enabled' => false,
            ],
            [
                'key' => 'monthly_cleaning_specific',
                'label' => 'Deep Cleaning Item Spesifik Store',
                'period' => 'monthly',
                'submission_type' => 'camera_only',
                'note_type' => 'Foto Bukti Cleaning',
                'group' => 'general_cleaning',
                'group_label' => 'General Cleaning',
                'sort_order' => 11,
                'deadline_time' => null,
                'deadline_day' => null,
                'deadline_enabled' => false,
            ],
        ];

        foreach ($tasks as $task) {
            BriefingTask::updateOrCreate(['key' => $task['key']], $task);
        }
    }
}
