---
deployment:
  tasks:
    - export DEPLOYPATH=/home/helh1723/public_html/helpbloomery
    - /usr/local/bin/php $DEPLOYPATH/artisan migrate --force --no-interaction
    - /usr/local/bin/php $DEPLOYPATH/artisan permissions:sync --no-interaction
    - /usr/local/bin/php $DEPLOYPATH/artisan db:seed --class=Database\\Seeders\\QualityControlChecklistSeeder --force --no-interaction
    - /usr/local/bin/php $DEPLOYPATH/artisan config:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan route:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan view:cache
