<details class="rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm text-blue-900 dark:border-blue-900 dark:bg-blue-950/30 dark:text-blue-200">
    <summary class="cursor-pointer font-semibold">Cara menghitung SLA ERP IT</summary>
    <div class="mt-3 space-y-2 text-xs leading-relaxed">
        <p><strong>Jam yang dihitung:</strong> Senin–Jumat, 08.00–17.00 WIB (Asia/Jakarta), yaitu 9 jam per hari. Sabtu, Minggu, sebelum 08.00, dan setelah 17.00 tidak dihitung. Jam istirahat dan hari libur nasional yang jatuh pada weekdays tetap dihitung.</p>
        <p><strong>Respons pertama:</strong> dari waktu Submitted sampai IT pertama kali mengubah status menjadi Review. Membuka tiket atau mengedit catatan belum dianggap respons.</p>
        <p><strong>Penyelesaian:</strong> dari Submitted sampai Completed, termasuk waktu tunggu review dan approval. Rejected tidak masuk rata-rata penyelesaian.</p>
        <p><strong>Rumus:</strong> jumlahkan irisan durasi setiap hari dengan 08.00–17.00. Rata-rata = total durasi valid ÷ jumlah tiket dengan durasi valid, menggunakan seluruh hasil filter daftar, bukan hanya halaman yang sedang tampil.</p>
        <p><strong>Contoh:</strong> Jumat 16.30 → Senin 09.30 = Jumat 30 menit + Senin 90 menit = 2 jam kerja. Sabtu 10.00 → Senin 08.30 = 30 menit kerja.</p>
        <p><strong>Ketepatan data:</strong> timestamp kejadian sebenarnya tetap disimpan, termasuk di luar jam kerja. Durasi dihitung dalam detik dan dibulatkan hanya saat ditampilkan. Durasi 0 tetap masuk sampel. Data historis tanpa timestamp yang pasti ditampilkan sebagai “Tidak tersedia” dan dikecualikan dari rata-rata.</p>
        <p><strong>Filter tanggal:</strong> menggunakan tanggal pengajuan (Submitted). Tiket belum direspons atau belum selesai belum masuk rata-rata metrik terkait. “Belum selesai” menghitung tiket aktif selain Completed dan Rejected.</p>
        <p><strong>KPI khusus Ticketing:</strong> Ticketing adalah masalah ringan. Project dan CMS dikecualikan dari kedua KPI. Pemrosesan data ERP = jumlah Ticketing Completed dalam ≤ 9 jam kerja ÷ seluruh permintaan Ticketing hasil filter × 100%, dengan target ≥ 98%. Completed untuk KPI ini berarti data sudah aktif di sistem.</p>
        <p><strong>Rata-rata tiket ringan:</strong> total durasi penyelesaian Ticketing Completed dengan data valid ÷ jumlah sampelnya, dengan target &lt; 4 jam kerja. Tepat 4 jam belum memenuhi target. Durasi ini mencakup antrean, review, dan approval sejak Submitted; bukan hanya waktu IT bekerja langsung.</p>
        <p><strong>Penilaian KPI:</strong> permintaan belum selesai, Rejected, dan Completed tanpa durasi valid tetap masuk pembagi KPI persentase, tetapi bukan pembilang tepat waktu. Data tanpa durasi valid tidak masuk rata-rata. Nilai ditandai sementara jika masih ada tiket aktif atau Completed tanpa durasi valid. Status target menggunakan angka asli sebelum pembulatan tampilan; seluruh filter, termasuk status, menentukan cakupan penilaian.</p>
    </div>
</details>
